# Generated by Django 4.1.3 on 2022-11-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
